base_images:
  cli:
    name: "4.11"
    namespace: origin
    tag: cli
  upi-installer:
    name: "4.11"
    namespace: ocp
    tag: upi-installer
build_root:
  from_repository: true
  use_build_cache: true
images:
- dockerfile_literal: |
    FROM registry.ci.openshift.org/origin/centos:stream8
    RUN curl --silent --location --output /usr/local/bin/openshift-provider-cert-linux-amd64 https://github.com/redhat-openshift-ecosystem/provider-certification-tool/releases/latest/download/openshift-provider-cert-linux-amd64 && \
        chmod +x /usr/local/bin/openshift-provider-cert-linux-amd64
  from: cli
  to: opct-image
releases:
  latest:
    release:
      channel: stable
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: provider-certification-tool-vsphere-ipi
  cron: 0 0 * * 2,4
  steps:
    cluster_profile: vsphere
    workflow: provider-certification-tool-vsphere-ipi
- as: provider-certification-tool-vsphere-upi-platform-none
  cron: 0 0 * * 1,3,5
  steps:
    cluster_profile: vsphere
    workflow: provider-certification-tool-vsphere-upi-platform-none
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: stable-4.11
