base_images:
  upi-installer:
    name: "4.11"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    release:
      channel: stable
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: provider-certification-tool-vsphere-ipi
  cron: 0 0 * * 2,4
  steps:
    cluster_profile: vsphere
    workflow: provider-certification-tool-vsphere-ipi
- as: provider-certification-tool-vsphere-upi-platform-none
  cron: 0 0 * * 1,3,5
  steps:
    cluster_profile: vsphere
    workflow: provider-certification-tool-vsphere-upi-platform-none
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: stable-4.11
