build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.18-openshift-4.11
resources:
  '*':
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: shellcheck
  commands: make shellcheck
  container:
    from: src
zz_generated_metadata:
  branch: mvp
  org: openshift
  repo: provider-certification-tool
